/**
 * Custom theme presets for Pretty Fish.
 * Each preset is a complete design system — colors, typography, curves, spacing.
 * Uses mermaid's 'base' theme with full themeVariables + DiagramConfig overrides.
 *
 * Every ThemePresetDef requires exhaustive vars for every diagram group.
 * Adding a new group to ThemeVariablesByDiagram will cause compile errors
 * here until every preset is updated.
 */

import type { DiagramConfig, MermaidLook } from '../types'
import type { ThemeVariablesByDiagram } from './mermaidThemeVariables'
import { flattenThemeVariables } from './mermaidThemeVariables'

export interface ThemePresetDef {
  label: string
  description: string
  vars: ThemeVariablesByDiagram
  configOverrides: Partial<{
    look: MermaidLook
    fontFamily: string
    fontSize: number
    flowchart: Partial<DiagramConfig['flowchart']>
    sequence: Partial<DiagramConfig['sequence']>
    gantt: Partial<DiagramConfig['gantt']>
    xyChart: Partial<{ plotColorPalette: string }>
  }>
}

/** Public-facing flattened preset (used by render pipeline). */
export interface ThemePreset {
  label: string
  description: string
  themeVariables: Record<string, string>
  configOverrides: ThemePresetDef['configOverrides']
}

function toPreset(def: ThemePresetDef): ThemePreset {
  return {
    label: def.label,
    description: def.description,
    themeVariables: flattenThemeVariables(def.vars) as unknown as Record<string, string>,
    configOverrides: def.configOverrides,
  }
}

// ── Theme definitions (exhaustive, type-checked) ─────────────────────────────

const DEFS: Record<string, ThemePresetDef> = {

  wireframe: {
    label: 'Wireframe',
    description: 'Sketch-style wireframe',
    configOverrides: {
      look: 'handDrawn',
      fontFamily: '"Caveat", cursive',
      fontSize: 18,
      flowchart: { curve: 'linear', nodeSpacing: 60, rankSpacing: 60, padding: 20 },
      sequence: { actorMargin: 60, messageMargin: 40 },
    },
    vars: {
      core: {
        background: '#ffffff',
        primaryColor: '#f5f5f5',
        primaryTextColor: '#333333',
        primaryBorderColor: '#888888',
        secondaryColor: '#eeeeee',
        secondaryTextColor: '#555555',
        secondaryBorderColor: '#aaaaaa',
        tertiaryColor: '#fafafa',
        tertiaryTextColor: '#666666',
        tertiaryBorderColor: '#cccccc',
        lineColor: '#777777',
        titleColor: '#333333',
        fontFamily: '"Caveat", cursive',
      },
      flowchart: {
        mainBkg: '#f5f5f5',
        nodeBorder: '#888888',
        nodeTextColor: '#333333',
        clusterBkg: '#fafafa',
        clusterBorder: '#cccccc',
        edgeLabelBackground: '#ffffff',
        defaultLinkColor: '#777777',
      },
      sequence: {
        actorBkg: '#f5f5f5',
        actorBorder: '#888888',
        actorTextColor: '#333333',
        actorLineColor: '#888888',
        signalColor: '#777777',
        signalTextColor: '#333333',
        labelBoxBkgColor: '#f5f5f5',
        labelBoxBorderColor: '#aaaaaa',
        labelTextColor: '#333333',
        loopTextColor: '#666666',
        activationBkgColor: '#eeeeee',
        activationBorderColor: '#999999',
        sequenceNumberColor: '#ffffff',
        noteBkgColor: '#fff9c4',
        noteTextColor: '#333333',
        noteBorderColor: '#e6d85e',
      },
      er: {
        attributeBackgroundColorOdd: '#ffffff',
        attributeBackgroundColorEven: '#f5f5f5',
      },
      state: {
        stateBkg: '#f5f5f5',
        stateLabelColor: '#333333',
        compositeBackground: '#fafafa',
        compositeTitleBackground: '#eeeeee',
        compositeBorder: '#aaaaaa',
        transitionColor: '#777777',
        transitionLabelColor: '#555555',
        specialStateColor: '#888888',
        errorBkgColor: '#ffdddd',
        errorTextColor: '#333333',
      },
      class: {
        classText: '#333333',
        fillType0: '#f5f5f5',
        fillType1: '#eeeeee',
        fillType2: '#e8e8e8',
        fillType3: '#dddddd',
        fillType4: '#d5d5d5',
        fillType5: '#cccccc',
        fillType6: '#c0c0c0',
        fillType7: '#b8b8b8',
      },
      gantt: {
        sectionBkgColor: '#f5f5f5',
        altSectionBkgColor: '#ffffff',
        taskBorderColor: '#888888',
        taskBkgColor: '#eeeeee',
        taskTextColor: '#333333',
        taskTextLightColor: '#ffffff',
        taskTextDarkColor: '#333333',
        taskTextOutsideColor: '#333333',
        activeTaskBorderColor: '#666666',
        activeTaskBkgColor: '#dddddd',
        doneTaskBkgColor: '#cccccc',
        doneTaskBorderColor: '#999999',
        critBkgColor: '#ffdddd',
        critBorderColor: '#cc0000',
        todayLineColor: '#cc0000',
      },
      git: {
        git0: '#888888',
        git1: '#aaaaaa',
        git2: '#666666',
        git3: '#999999',
        git4: '#777777',
        git5: '#bbbbbb',
        git6: '#555555',
        git7: '#888888',
        gitBranchLabel0: '#ffffff',
        gitBranchLabel1: '#333333',
        gitBranchLabel2: '#ffffff',
        gitBranchLabel3: '#333333',
        gitBranchLabel4: '#ffffff',
        gitBranchLabel5: '#333333',
        gitBranchLabel6: '#ffffff',
        gitBranchLabel7: '#ffffff',
      },
      pie: {
        pie1: '#f5f5f5',
        pie2: '#dddddd',
        pie3: '#cccccc',
        pie4: '#bbbbbb',
        pie5: '#aaaaaa',
        pie6: '#999999',
        pie7: '#888888',
        pie8: '#777777',
        pieTitleTextColor: '#333333',
        pieSectionTextColor: '#333333',
        pieStrokeColor: '#888888',
      },
      requirement: {
        requirementBackground: '#f5f5f5',
        requirementBorderColor: '#888888',
        requirementTextColor: '#333333',
        relationColor: '#777777',
        relationLabelBackground: '#ffffff',
        relationLabelColor: '#555555',
      },
      quadrant: {
        quadrant1Fill: '#f5f5f5',
        quadrant2Fill: '#eeeeee',
        quadrant3Fill: '#e8e8e8',
        quadrant4Fill: '#f0f0f0',
        quadrant1TextFill: '#333333',
        quadrant2TextFill: '#333333',
        quadrant3TextFill: '#333333',
        quadrant4TextFill: '#333333',
        quadrantPointFill: '#888888',
        quadrantPointTextFill: '#333333',
        quadrantXAxisTextFill: '#555555',
        quadrantYAxisTextFill: '#555555',
        quadrantTitleFill: '#333333',
      },
      architecture: {
        archEdgeColor: '#777777',
        archEdgeArrowColor: '#777777',
        archGroupBorderColor: '#888888',
      },
      journey: {
        cScale0: '#f5f5f5',
        cScale1: '#eeeeee',
        cScale2: '#e0e0e0',
        cScale3: '#d5d5d5',
        cScale4: '#cccccc',
        cScale5: '#bbbbbb',
        cScale6: '#aaaaaa',
        cScale7: '#999999',
        cScale8: '#888888',
        cScale9: '#777777',
        cScale10: '#666666',
        cScale11: '#555555',
      },
    },
  },

  corporate: {
    label: 'Corporate',
    description: 'Clean business pastels',
    configOverrides: {
      look: 'classic',
      fontFamily: '"Source Sans 3", "Segoe UI", sans-serif',
      fontSize: 15,
      flowchart: { curve: 'monotoneX', nodeSpacing: 55, rankSpacing: 55, padding: 18 },
      sequence: { actorMargin: 55, messageMargin: 38, width: 160 },
      gantt: { barHeight: 24, barGap: 6 },
      xyChart: { plotColorPalette: '#3b82f6,#0ea5e9,#06b6d4,#6366f1,#8b5cf6,#64748b' },
    },
    vars: {
      core: {
        background: '#ffffff',
        primaryColor: '#dbeafe',
        primaryTextColor: '#1e293b',
        primaryBorderColor: '#93c5fd',
        secondaryColor: '#ccfbf1',
        secondaryTextColor: '#1e293b',
        secondaryBorderColor: '#5eead4',
        tertiaryColor: '#e0f2fe',
        tertiaryTextColor: '#1e293b',
        tertiaryBorderColor: '#7dd3fc',
        lineColor: '#94a3b8',
        titleColor: '#0f172a',
        fontFamily: '"Source Sans 3", "Segoe UI", sans-serif',
      },
      flowchart: {
        mainBkg: '#dbeafe',
        nodeBorder: '#93c5fd',
        nodeTextColor: '#1e293b',
        clusterBkg: '#f8fafc',
        clusterBorder: '#cbd5e1',
        edgeLabelBackground: '#ffffff',
        defaultLinkColor: '#94a3b8',
      },
      sequence: {
        actorBkg: '#dbeafe',
        actorBorder: '#93c5fd',
        actorTextColor: '#1e293b',
        actorLineColor: '#93c5fd',
        signalColor: '#64748b',
        signalTextColor: '#1e293b',
        labelBoxBkgColor: '#ccfbf1',
        labelBoxBorderColor: '#5eead4',
        labelTextColor: '#1e293b',
        loopTextColor: '#475569',
        activationBkgColor: '#bfdbfe',
        activationBorderColor: '#60a5fa',
        sequenceNumberColor: '#ffffff',
        noteBkgColor: '#fef9c3',
        noteTextColor: '#1e293b',
        noteBorderColor: '#fde047',
      },
      er: {
        attributeBackgroundColorOdd: '#ffffff',
        attributeBackgroundColorEven: '#f0f7ff',
      },
      state: {
        stateBkg: '#dbeafe',
        stateLabelColor: '#1e293b',
        compositeBackground: '#f8fafc',
        compositeTitleBackground: '#e0f2fe',
        compositeBorder: '#93c5fd',
        transitionColor: '#94a3b8',
        transitionLabelColor: '#475569',
        specialStateColor: '#3b82f6',
        errorBkgColor: '#fee2e2',
        errorTextColor: '#991b1b',
      },
      class: {
        classText: '#1e293b',
        fillType0: '#dbeafe',
        fillType1: '#ccfbf1',
        fillType2: '#e0f2fe',
        fillType3: '#bfdbfe',
        fillType4: '#a5f3fc',
        fillType5: '#bae6fd',
        fillType6: '#dbeafe',
        fillType7: '#ccfbf1',
      },
      gantt: {
        sectionBkgColor: '#eff6ff',
        altSectionBkgColor: '#ffffff',
        taskBorderColor: '#93c5fd',
        taskBkgColor: '#dbeafe',
        taskTextColor: '#1e293b',
        taskTextLightColor: '#ffffff',
        taskTextDarkColor: '#1e293b',
        taskTextOutsideColor: '#1e293b',
        activeTaskBorderColor: '#3b82f6',
        activeTaskBkgColor: '#bfdbfe',
        doneTaskBkgColor: '#94a3b8',
        doneTaskBorderColor: '#64748b',
        critBkgColor: '#fee2e2',
        critBorderColor: '#ef4444',
        todayLineColor: '#3b82f6',
      },
      git: {
        git0: '#3b82f6',
        git1: '#0ea5e9',
        git2: '#06b6d4',
        git3: '#6366f1',
        git4: '#8b5cf6',
        git5: '#64748b',
        git6: '#0284c7',
        git7: '#0369a1',
        gitBranchLabel0: '#ffffff',
        gitBranchLabel1: '#ffffff',
        gitBranchLabel2: '#ffffff',
        gitBranchLabel3: '#ffffff',
        gitBranchLabel4: '#ffffff',
        gitBranchLabel5: '#ffffff',
        gitBranchLabel6: '#ffffff',
        gitBranchLabel7: '#ffffff',
      },
      pie: {
        pie1: '#3b82f6',
        pie2: '#0ea5e9',
        pie3: '#06b6d4',
        pie4: '#6366f1',
        pie5: '#8b5cf6',
        pie6: '#64748b',
        pie7: '#0284c7',
        pie8: '#0369a1',
        pieTitleTextColor: '#0f172a',
        pieSectionTextColor: '#ffffff',
        pieStrokeColor: '#ffffff',
      },
      requirement: {
        requirementBackground: '#dbeafe',
        requirementBorderColor: '#93c5fd',
        requirementTextColor: '#1e293b',
        relationColor: '#94a3b8',
        relationLabelBackground: '#ffffff',
        relationLabelColor: '#475569',
      },
      quadrant: {
        quadrant1Fill: '#dbeafe',
        quadrant2Fill: '#e0f2fe',
        quadrant3Fill: '#ccfbf1',
        quadrant4Fill: '#eff6ff',
        quadrant1TextFill: '#1e293b',
        quadrant2TextFill: '#1e293b',
        quadrant3TextFill: '#1e293b',
        quadrant4TextFill: '#1e293b',
        quadrantPointFill: '#3b82f6',
        quadrantPointTextFill: '#ffffff',
        quadrantXAxisTextFill: '#475569',
        quadrantYAxisTextFill: '#475569',
        quadrantTitleFill: '#0f172a',
      },
      architecture: {
        archEdgeColor: '#94a3b8',
        archEdgeArrowColor: '#94a3b8',
        archGroupBorderColor: '#93c5fd',
      },
      journey: {
        cScale0: '#dbeafe',
        cScale1: '#bfdbfe',
        cScale2: '#93c5fd',
        cScale3: '#60a5fa',
        cScale4: '#3b82f6',
        cScale5: '#2563eb',
        cScale6: '#1d4ed8',
        cScale7: '#0ea5e9',
        cScale8: '#06b6d4',
        cScale9: '#6366f1',
        cScale10: '#8b5cf6',
        cScale11: '#64748b',
      },
    },
  },
  amethyst: {
    label: 'Amethyst',
    description: 'Rich purple palette',
    configOverrides: {
      look: 'classic',
      fontFamily: '"Poppins", sans-serif',
      fontSize: 14,
      flowchart: { curve: 'cardinal', nodeSpacing: 44, rankSpacing: 50, padding: 14 },
      sequence: { actorMargin: 45, messageMargin: 30, width: 140 },
      xyChart: { plotColorPalette: '#7c3aed,#a78bfa,#6d28d9,#c4b5fd,#5b21b6,#ddd6fe' },
    },
    vars: {
      core: {
        background: '#ffffff',
        primaryColor: '#ede9fe',
        primaryTextColor: '#3b0764',
        primaryBorderColor: '#7c3aed',
        secondaryColor: '#7c3aed',
        secondaryTextColor: '#ffffff',
        secondaryBorderColor: '#6d28d9',
        tertiaryColor: '#ddd6fe',
        tertiaryTextColor: '#3b0764',
        tertiaryBorderColor: '#a78bfa',
        lineColor: '#7c3aed',
        titleColor: '#4c1d95',
        fontFamily: '"Poppins", sans-serif',
      },
      flowchart: {
        mainBkg: '#ede9fe',
        nodeBorder: '#7c3aed',
        nodeTextColor: '#3b0764',
        clusterBkg: '#f5f3ff',
        clusterBorder: '#a78bfa',
        edgeLabelBackground: '#faf5ff',
        defaultLinkColor: '#7c3aed',
      },
      sequence: {
        actorBkg: '#7c3aed',
        actorBorder: '#6d28d9',
        actorTextColor: '#ffffff',
        actorLineColor: '#6d28d9',
        signalColor: '#6d28d9',
        signalTextColor: '#4c1d95',
        labelBoxBkgColor: '#ede9fe',
        labelBoxBorderColor: '#a78bfa',
        labelTextColor: '#3b0764',
        loopTextColor: '#6d28d9',
        activationBkgColor: '#c4b5fd',
        activationBorderColor: '#7c3aed',
        sequenceNumberColor: '#ffffff',
        noteBkgColor: '#f5f3ff',
        noteTextColor: '#4c1d95',
        noteBorderColor: '#c4b5fd',
      },
      er: {
        attributeBackgroundColorOdd: '#f5f3ff',
        attributeBackgroundColorEven: '#ede9fe',
      },
      state: {
        stateBkg: '#ede9fe',
        stateLabelColor: '#3b0764',
        compositeBackground: '#f5f3ff',
        compositeTitleBackground: '#ddd6fe',
        compositeBorder: '#a78bfa',
        transitionColor: '#7c3aed',
        transitionLabelColor: '#4c1d95',
        specialStateColor: '#6d28d9',
        errorBkgColor: '#fee2e2',
        errorTextColor: '#991b1b',
      },
      class: {
        classText: '#3b0764',
        fillType0: '#ede9fe',
        fillType1: '#ddd6fe',
        fillType2: '#c4b5fd',
        fillType3: '#a78bfa',
        fillType4: '#8b5cf6',
        fillType5: '#7c3aed',
        fillType6: '#6d28d9',
        fillType7: '#5b21b6',
      },
      gantt: {
        sectionBkgColor: '#f5f3ff',
        altSectionBkgColor: '#ffffff',
        taskBorderColor: '#7c3aed',
        taskBkgColor: '#ede9fe',
        taskTextColor: '#3b0764',
        taskTextLightColor: '#ffffff',
        taskTextDarkColor: '#3b0764',
        taskTextOutsideColor: '#3b0764',
        activeTaskBorderColor: '#6d28d9',
        activeTaskBkgColor: '#ddd6fe',
        doneTaskBkgColor: '#a78bfa',
        doneTaskBorderColor: '#7c3aed',
        critBkgColor: '#fee2e2',
        critBorderColor: '#ef4444',
        todayLineColor: '#6d28d9',
      },
      git: {
        git0: '#7c3aed',
        git1: '#6d28d9',
        git2: '#a78bfa',
        git3: '#8b5cf6',
        git4: '#4c1d95',
        git5: '#c4b5fd',
        git6: '#5b21b6',
        git7: '#7c3aed',
        gitBranchLabel0: '#ffffff',
        gitBranchLabel1: '#ffffff',
        gitBranchLabel2: '#3b0764',
        gitBranchLabel3: '#ffffff',
        gitBranchLabel4: '#ffffff',
        gitBranchLabel5: '#3b0764',
        gitBranchLabel6: '#ffffff',
        gitBranchLabel7: '#ffffff',
      },
      pie: {
        pie1: '#7c3aed',
        pie2: '#a78bfa',
        pie3: '#6d28d9',
        pie4: '#c4b5fd',
        pie5: '#5b21b6',
        pie6: '#ddd6fe',
        pie7: '#8b5cf6',
        pie8: '#4c1d95',
        pieTitleTextColor: '#4c1d95',
        pieSectionTextColor: '#ffffff',
        pieStrokeColor: '#ffffff',
      },
      requirement: {
        requirementBackground: '#ede9fe',
        requirementBorderColor: '#7c3aed',
        requirementTextColor: '#3b0764',
        relationColor: '#7c3aed',
        relationLabelBackground: '#f5f3ff',
        relationLabelColor: '#4c1d95',
      },
      quadrant: {
        quadrant1Fill: '#ede9fe',
        quadrant2Fill: '#ddd6fe',
        quadrant3Fill: '#f5f3ff',
        quadrant4Fill: '#faf5ff',
        quadrant1TextFill: '#3b0764',
        quadrant2TextFill: '#3b0764',
        quadrant3TextFill: '#3b0764',
        quadrant4TextFill: '#3b0764',
        quadrantPointFill: '#7c3aed',
        quadrantPointTextFill: '#ffffff',
        quadrantXAxisTextFill: '#4c1d95',
        quadrantYAxisTextFill: '#4c1d95',
        quadrantTitleFill: '#4c1d95',
      },
      architecture: {
        archEdgeColor: '#7c3aed',
        archEdgeArrowColor: '#7c3aed',
        archGroupBorderColor: '#a78bfa',
      },
      journey: {
        cScale0: '#ede9fe',
        cScale1: '#ddd6fe',
        cScale2: '#c4b5fd',
        cScale3: '#a78bfa',
        cScale4: '#8b5cf6',
        cScale5: '#7c3aed',
        cScale6: '#6d28d9',
        cScale7: '#5b21b6',
        cScale8: '#4c1d95',
        cScale9: '#3b0764',
        cScale10: '#f5f3ff',
        cScale11: '#faf5ff',
      },
    },
  },

  neon: {
    label: 'Neon',
    description: 'Electric brutalist colors',
    configOverrides: {
      look: 'classic',
      fontFamily: '"Space Mono", monospace',
      fontSize: 13,
      flowchart: { curve: 'step', nodeSpacing: 45, rankSpacing: 50, padding: 10 },
      sequence: { showSequenceNumbers: true, actorMargin: 40, messageMargin: 30, width: 130 },
      gantt: { barHeight: 28, barGap: 2 },
      xyChart: { plotColorPalette: '#2d2dff,#ff2d9b,#00cc44,#ff8800,#00cccc,#cc00ff,#ffcc00' },
    },
    vars: {
      core: {
        background: '#ffffff',
        primaryColor: '#2d2dff',
        primaryTextColor: '#ffffff',
        primaryBorderColor: '#000000',
        secondaryColor: '#ff2d9b',
        secondaryTextColor: '#ffffff',
        secondaryBorderColor: '#000000',
        tertiaryColor: '#e8ff00',
        tertiaryTextColor: '#000000',
        tertiaryBorderColor: '#000000',
        lineColor: '#111111',
        titleColor: '#000000',
        fontFamily: '"Space Mono", monospace',
      },
      flowchart: {
        mainBkg: '#2d2dff',
        nodeBorder: '#000000',
        nodeTextColor: '#ffffff',
        clusterBkg: '#e8ff00',
        clusterBorder: '#000000',
        edgeLabelBackground: '#e8ff00',
        defaultLinkColor: '#111111',
      },
      sequence: {
        actorBkg: '#2d2dff',
        actorBorder: '#000000',
        actorTextColor: '#ffffff',
        actorLineColor: '#000000',
        signalColor: '#000000',
        signalTextColor: '#000000',
        labelBoxBkgColor: '#ff2d9b',
        labelBoxBorderColor: '#000000',
        labelTextColor: '#ffffff',
        loopTextColor: '#000000',
        activationBkgColor: '#e8ff00',
        activationBorderColor: '#000000',
        sequenceNumberColor: '#ffffff',
        noteBkgColor: '#e8ff00',
        noteTextColor: '#000000',
        noteBorderColor: '#000000',
      },
      er: {
        attributeBackgroundColorOdd: '#1a1acc',
        attributeBackgroundColorEven: '#2d2dff',
      },
      state: {
        stateBkg: '#2d2dff',
        stateLabelColor: '#ffffff',
        compositeBackground: '#f0f0ff',
        compositeTitleBackground: '#e8ff00',
        compositeBorder: '#000000',
        transitionColor: '#111111',
        transitionLabelColor: '#000000',
        specialStateColor: '#ff2d9b',
        errorBkgColor: '#ff2d9b',
        errorTextColor: '#ffffff',
      },
      class: {
        classText: '#ffffff',
        fillType0: '#2d2dff',
        fillType1: '#ff2d9b',
        fillType2: '#e8ff00',
        fillType3: '#00cc44',
        fillType4: '#ff8800',
        fillType5: '#00cccc',
        fillType6: '#cc00ff',
        fillType7: '#ffcc00',
      },
      gantt: {
        sectionBkgColor: '#e8e8ff',
        altSectionBkgColor: '#ffffff',
        taskBorderColor: '#000000',
        taskBkgColor: '#2d2dff',
        taskTextColor: '#ffffff',
        taskTextLightColor: '#ffffff',
        taskTextDarkColor: '#000000',
        taskTextOutsideColor: '#000000',
        activeTaskBorderColor: '#000000',
        activeTaskBkgColor: '#ff2d9b',
        doneTaskBkgColor: '#00cc44',
        doneTaskBorderColor: '#000000',
        critBkgColor: '#ff8800',
        critBorderColor: '#000000',
        todayLineColor: '#ff2d9b',
      },
      git: {
        git0: '#2d2dff',
        git1: '#ff2d9b',
        git2: '#00cc44',
        git3: '#ff8800',
        git4: '#00cccc',
        git5: '#cc00ff',
        git6: '#ffcc00',
        git7: '#2d2dff',
        gitBranchLabel0: '#ffffff',
        gitBranchLabel1: '#ffffff',
        gitBranchLabel2: '#000000',
        gitBranchLabel3: '#000000',
        gitBranchLabel4: '#000000',
        gitBranchLabel5: '#ffffff',
        gitBranchLabel6: '#000000',
        gitBranchLabel7: '#ffffff',
      },
      pie: {
        pie1: '#2d2dff',
        pie2: '#ff2d9b',
        pie3: '#e8ff00',
        pie4: '#00cc44',
        pie5: '#ff8800',
        pie6: '#00cccc',
        pie7: '#cc00ff',
        pie8: '#ffcc00',
        pieTitleTextColor: '#000000',
        pieSectionTextColor: '#000000',
        pieStrokeColor: '#000000',
      },
      requirement: {
        requirementBackground: '#e8e8ff',
        requirementBorderColor: '#000000',
        requirementTextColor: '#000000',
        relationColor: '#111111',
        relationLabelBackground: '#e8ff00',
        relationLabelColor: '#000000',
      },
      quadrant: {
        quadrant1Fill: '#2d2dff',
        quadrant2Fill: '#ff2d9b',
        quadrant3Fill: '#e8ff00',
        quadrant4Fill: '#00cccc',
        quadrant1TextFill: '#ffffff',
        quadrant2TextFill: '#ffffff',
        quadrant3TextFill: '#000000',
        quadrant4TextFill: '#000000',
        quadrantPointFill: '#ff8800',
        quadrantPointTextFill: '#000000',
        quadrantXAxisTextFill: '#000000',
        quadrantYAxisTextFill: '#000000',
        quadrantTitleFill: '#000000',
      },
      architecture: {
        archEdgeColor: '#111111',
        archEdgeArrowColor: '#111111',
        archGroupBorderColor: '#000000',
      },
      journey: {
        cScale0: '#2d2dff',
        cScale1: '#ff2d9b',
        cScale2: '#e8ff00',
        cScale3: '#00cc44',
        cScale4: '#ff8800',
        cScale5: '#00cccc',
        cScale6: '#cc00ff',
        cScale7: '#ffcc00',
        cScale8: '#2d2dff',
        cScale9: '#ff2d9b',
        cScale10: '#e8ff00',
        cScale11: '#00cc44',
      },
    },
  },

  blueprint: {
    label: 'Blueprint',
    description: 'Technical blueprint with deep navy borders and monospace font',
    configOverrides: {
      look: 'classic' as const,
      fontFamily: '"JetBrains Mono", monospace',
      fontSize: 13,
      flowchart: { curve: 'linear' as const, nodeSpacing: 48, rankSpacing: 52, padding: 16, diagramPadding: 10 },
      sequence: { showSequenceNumbers: false, mirrorActors: false, messageMargin: 30, actorMargin: 50, width: 140 },
      gantt: { barHeight: 18, barGap: 4, topPadding: 48, axisFormat: '%Y-%m-%d' },
    },
    vars: {
      core: {
        background: '#f5f8ff',
        primaryColor: '#e8eef8',
        primaryTextColor: '#0a2d6b',
        primaryBorderColor: '#0a2d6b',
        secondaryColor: '#e8f0ff',
        secondaryTextColor: '#1a3a8a',
        secondaryBorderColor: '#1a3a8a',
        tertiaryColor: '#edf1fb',
        tertiaryTextColor: '#2a4a7a',
        tertiaryBorderColor: '#2a4a7a',
        lineColor: '#1a4a9a',
        titleColor: '#0a2d6b',
        fontFamily: '"JetBrains Mono", monospace',
      },
      flowchart: {
        mainBkg: '#e8eef8',
        nodeBorder: '#0a2d6b',
        nodeTextColor: '#0a2d6b',
        clusterBkg: '#eef2fc',
        clusterBorder: '#1a4a9a',
        edgeLabelBackground: '#f0f4ff',
        defaultLinkColor: '#1a4a9a',
      },
      sequence: {
        actorBkg: '#e8eef8',
        actorBorder: '#0a2d6b',
        actorTextColor: '#0a2d6b',
        actorLineColor: '#0a2d6b',
        signalColor: '#0a2d6b',
        signalTextColor: '#0a2d6b',
        labelBoxBkgColor: '#e8eef8',
        labelBoxBorderColor: '#0a2d6b',
        labelTextColor: '#0a2d6b',
        loopTextColor: '#0a2d6b',
        activationBkgColor: '#c8d8f0',
        activationBorderColor: '#0a2d6b',
        sequenceNumberColor: '#ffffff',
        noteBkgColor: '#eef3ff',
        noteTextColor: '#0a2d6b',
        noteBorderColor: '#1a4a9a',
      },
      er: {
        attributeBackgroundColorOdd: '#f5f8ff',
        attributeBackgroundColorEven: '#e8eef8',
      },
      state: {
        stateBkg: '#e8eef8',
        stateLabelColor: '#0a2d6b',
        compositeBackground: '#eef2fc',
        compositeTitleBackground: '#d8e4f4',
        compositeBorder: '#0a2d6b',
        transitionColor: '#1a4a9a',
        transitionLabelColor: '#0a2d6b',
        specialStateColor: '#1a4a9a',
        errorBkgColor: '#fee2e2',
        errorTextColor: '#991b1b',
      },
      class: {
        classText: '#0a2d6b',
        fillType0: '#e8eef8',
        fillType1: '#e8f0ff',
        fillType2: '#edf1fb',
        fillType3: '#d8e4f4',
        fillType4: '#c8d8f0',
        fillType5: '#b8cce8',
        fillType6: '#a8c0e0',
        fillType7: '#98b4d8',
      },
      gantt: {
        sectionBkgColor: '#eef2fc',
        altSectionBkgColor: '#f5f8ff',
        taskBorderColor: '#0a2d6b',
        taskBkgColor: '#e8eef8',
        taskTextColor: '#0a2d6b',
        taskTextLightColor: '#ffffff',
        taskTextDarkColor: '#0a2d6b',
        taskTextOutsideColor: '#0a2d6b',
        activeTaskBorderColor: '#0a2d6b',
        activeTaskBkgColor: '#c8d8f0',
        doneTaskBkgColor: '#94a3b8',
        doneTaskBorderColor: '#64748b',
        critBkgColor: '#fee2e2',
        critBorderColor: '#ef4444',
        todayLineColor: '#1a4a9a',
      },
      git: {
        git0: '#0a2d6b',
        git1: '#1a4a9a',
        git2: '#2a5aaa',
        git3: '#3a6aba',
        git4: '#4a7aca',
        git5: '#5a8ada',
        git6: '#1a3a8a',
        git7: '#0a2d6b',
        gitBranchLabel0: '#ffffff',
        gitBranchLabel1: '#ffffff',
        gitBranchLabel2: '#ffffff',
        gitBranchLabel3: '#ffffff',
        gitBranchLabel4: '#000000',
        gitBranchLabel5: '#000000',
        gitBranchLabel6: '#ffffff',
        gitBranchLabel7: '#ffffff',
      },
      pie: {
        pie1: '#0a2d6b',
        pie2: '#1a4a9a',
        pie3: '#2a5aaa',
        pie4: '#3a6aba',
        pie5: '#4a7aca',
        pie6: '#5a8ada',
        pie7: '#1a3a8a',
        pie8: '#0a2d6b',
        pieTitleTextColor: '#0a2d6b',
        pieSectionTextColor: '#ffffff',
        pieStrokeColor: '#f5f8ff',
      },
      requirement: {
        requirementBackground: '#e8eef8',
        requirementBorderColor: '#0a2d6b',
        requirementTextColor: '#0a2d6b',
        relationColor: '#1a4a9a',
        relationLabelBackground: '#f0f4ff',
        relationLabelColor: '#0a2d6b',
      },
      quadrant: {
        quadrant1Fill: '#e8eef8',
        quadrant2Fill: '#d8e4f4',
        quadrant3Fill: '#eef2fc',
        quadrant4Fill: '#f0f4ff',
        quadrant1TextFill: '#0a2d6b',
        quadrant2TextFill: '#0a2d6b',
        quadrant3TextFill: '#0a2d6b',
        quadrant4TextFill: '#0a2d6b',
        quadrantPointFill: '#0a2d6b',
        quadrantPointTextFill: '#ffffff',
        quadrantXAxisTextFill: '#0a2d6b',
        quadrantYAxisTextFill: '#0a2d6b',
        quadrantTitleFill: '#0a2d6b',
      },
      architecture: {
        archEdgeColor: '#1a4a9a',
        archEdgeArrowColor: '#1a4a9a',
        archGroupBorderColor: '#0a2d6b',
      },
      journey: {
        cScale0: '#e8eef8',
        cScale1: '#d8e4f4',
        cScale2: '#c8d8f0',
        cScale3: '#b8cce8',
        cScale4: '#a8c0e0',
        cScale5: '#98b4d8',
        cScale6: '#88a8d0',
        cScale7: '#789cc8',
        cScale8: '#6890c0',
        cScale9: '#5884b8',
        cScale10: '#4878b0',
        cScale11: '#386ca8',
      },
    },
  },
}

export const CUSTOM_THEME_PRESETS: Record<string, ThemePreset> = Object.fromEntries(
  Object.entries(DEFS).map(([k, def]) => [k, toPreset(def)])
)

export const CUSTOM_THEME_IDS = Object.keys(CUSTOM_THEME_PRESETS) as (keyof typeof CUSTOM_THEME_PRESETS)[]
