import type { ThemePresetDef } from '../themePresetDefs'

const amethyst: ThemePresetDef = {
  label: 'Amethyst',
  description: 'Rich purple palette',
  disabled: true,
  configOverrides: {
    look: 'classic',
    fontFamily: '"Poppins", sans-serif',
    fontSize: 14,
    flowchart: { curve: 'cardinal', nodeSpacing: 44, rankSpacing: 50, padding: 14 },
    sequence: { actorMargin: 45, messageMargin: 30, width: 140 },
  },
  vars: {
    core: {
      background: '#ffffff',
      primaryColor: '#ede9fe',
      primaryTextColor: '#3b0764',
      primaryBorderColor: '#7c3aed',
      secondaryColor: '#7c3aed',
      secondaryTextColor: '#ffffff',
      secondaryBorderColor: '#6d28d9',
      tertiaryColor: '#ddd6fe',
      tertiaryTextColor: '#3b0764',
      tertiaryBorderColor: '#a78bfa',
      lineColor: '#7c3aed',
      titleColor: '#4c1d95',
      fontFamily: '"Poppins", sans-serif',
    },
    flowchart: {
      mainBkg: '#ede9fe',
      nodeBorder: '#7c3aed',
      nodeTextColor: '#3b0764',
      clusterBkg: '#f5f3ff',
      clusterBorder: '#a78bfa',
      edgeLabelBackground: '#faf5ff',
      defaultLinkColor: '#7c3aed',
    },
    sequence: {
      actorBkg: '#7c3aed',
      actorBorder: '#6d28d9',
      actorTextColor: '#ffffff',
      actorLineColor: '#6d28d9',
      signalColor: '#6d28d9',
      signalTextColor: '#4c1d95',
      labelBoxBkgColor: '#ede9fe',
      labelBoxBorderColor: '#a78bfa',
      labelTextColor: '#3b0764',
      loopTextColor: '#6d28d9',
      activationBkgColor: '#c4b5fd',
      activationBorderColor: '#7c3aed',
      sequenceNumberColor: '#ffffff',
      noteBkgColor: '#f5f3ff',
      noteTextColor: '#4c1d95',
      noteBorderColor: '#c4b5fd',
    },
    er: {
      attributeBackgroundColorOdd: '#f5f3ff',
      attributeBackgroundColorEven: '#ede9fe',
    },
    state: {
      stateBkg: '#ede9fe',
      stateLabelColor: '#3b0764',
      compositeBackground: '#f5f3ff',
      compositeTitleBackground: '#ddd6fe',
      compositeBorder: '#a78bfa',
      transitionColor: '#7c3aed',
      transitionLabelColor: '#4c1d95',
      specialStateColor: '#6d28d9',
      errorBkgColor: '#fee2e2',
      errorTextColor: '#991b1b',
    },
    class: {
      classText: '#ffffff',
      fillType0: '#7c3aed',
      fillType1: '#6d28d9',
      fillType2: '#5b21b6',
      fillType3: '#4c1d95',
      fillType4: '#8b5cf6',
      fillType5: '#7c3aed',
      fillType6: '#6d28d9',
      fillType7: '#5b21b6',
    },
    gantt: {
      sectionBkgColor: '#f5f3ff',
      altSectionBkgColor: '#ffffff',
      taskBorderColor: '#7c3aed',
      taskBkgColor: '#ede9fe',
      taskTextColor: '#3b0764',
      taskTextLightColor: '#3b0764',
      taskTextDarkColor: '#3b0764',
      taskTextOutsideColor: '#3b0764',
      activeTaskBorderColor: '#6d28d9',
      activeTaskBkgColor: '#ddd6fe',
      doneTaskBkgColor: '#a78bfa',
      doneTaskBorderColor: '#7c3aed',
      critBkgColor: '#fee2e2',
      critBorderColor: '#ef4444',
      todayLineColor: '#6d28d9',
    },
    git: {
      git0: '#7c3aed',
      git1: '#6d28d9',
      git2: '#a78bfa',
      git3: '#8b5cf6',
      git4: '#4c1d95',
      git5: '#c4b5fd',
      git6: '#5b21b6',
      git7: '#7c3aed',
      commitLabelColor: '#3b0764',
      commitLabelBackground: '#ede9fe',
      gitBranchLabel0: '#3b0764',
      gitBranchLabel1: '#3b0764',
      gitBranchLabel2: '#3b0764',
      gitBranchLabel3: '#000000',
      gitBranchLabel4: '#3b0764',
      gitBranchLabel5: '#3b0764',
      gitBranchLabel6: '#3b0764',
      gitBranchLabel7: '#3b0764',
    },
    pie: {
      pie1: '#7c3aed',
      pie2: '#8b5cf6',
      pie3: '#6d28d9',
      pie4: '#7c3aed',
      pie5: '#5b21b6',
      pie6: '#6d28d9',
      pie7: '#8b5cf6',
      pie8: '#4c1d95',
      pieTitleTextColor: '#4c1d95',
      pieSectionTextColor: '#ffffff',
      pieStrokeColor: '#ffffff',
    },
    requirement: {
      requirementBackground: '#ede9fe',
      requirementBorderColor: '#7c3aed',
      requirementTextColor: '#3b0764',
      relationColor: '#7c3aed',
      relationLabelBackground: '#f5f3ff',
      relationLabelColor: '#4c1d95',
    },
    quadrant: {
      quadrant1Fill: '#ede9fe',
      quadrant2Fill: '#ddd6fe',
      quadrant3Fill: '#f5f3ff',
      quadrant4Fill: '#faf5ff',
      quadrant1TextFill: '#3b0764',
      quadrant2TextFill: '#3b0764',
      quadrant3TextFill: '#3b0764',
      quadrant4TextFill: '#3b0764',
      quadrantPointFill: '#7c3aed',
      quadrantPointTextFill: '#ffffff',
      quadrantXAxisTextFill: '#4c1d95',
      quadrantYAxisTextFill: '#4c1d95',
      quadrantTitleFill: '#4c1d95',
    },
    architecture: {
      archEdgeColor: '#7c3aed',
      archEdgeArrowColor: '#7c3aed',
      archGroupBorderColor: '#a78bfa',
    },
    xyChart: {
      plotColorPalette: '#7c3aed,#a78bfa,#6d28d9,#c4b5fd,#5b21b6,#ddd6fe',
    },

    journey: {
      scaleLabelColor: '#ffffff',
      cScale0: '#ede9fe', cScaleLabel0: '#1a1a1a',
      cScale1: '#ddd6fe', cScaleLabel1: '#1a1a1a',
      cScale2: '#c4b5fd', cScaleLabel2: '#1a1a1a',
      cScale3: '#a78bfa', cScaleLabel3: '#1a1a1a',
      cScale4: '#8b5cf6', cScaleLabel4: '#ffffff',
      cScale5: '#7c3aed', cScaleLabel5: '#ffffff',
      cScale6: '#6d28d9', cScaleLabel6: '#ffffff',
      cScale7: '#5b21b6', cScaleLabel7: '#ffffff',
      cScale8: '#4c1d95', cScaleLabel8: '#ffffff',
      cScale9: '#3b0764', cScaleLabel9: '#ffffff',
      cScale10: '#f5f3ff', cScaleLabel10: '#1a1a1a',
      cScale11: '#faf5ff', cScaleLabel11: '#1a1a1a',
    },
  },
}

export default amethyst satisfies ThemePresetDef
