import type { ThemePresetDef } from '../themePresetDefs'

const corporate: ThemePresetDef = {
  label: 'Corporate',
  description: 'Clean business pastels',
  configOverrides: {
    look: 'classic',
    fontFamily: '"Source Sans 3", "Segoe UI", sans-serif',
    fontSize: 15,
    flowchart: { curve: 'monotoneX', nodeSpacing: 55, rankSpacing: 55, padding: 18 },
    sequence: { actorMargin: 55, messageMargin: 38, width: 160 },
    gantt: { barHeight: 24, barGap: 6 },
  },
  vars: {
    core: {
      background: '#ffffff',
      primaryColor: '#dbeafe',
      primaryTextColor: '#1e293b',
      primaryBorderColor: '#93c5fd',
      secondaryColor: '#ccfbf1',
      secondaryTextColor: '#1e293b',
      secondaryBorderColor: '#5eead4',
      tertiaryColor: '#e0f2fe',
      tertiaryTextColor: '#1e293b',
      tertiaryBorderColor: '#7dd3fc',
      lineColor: '#94a3b8',
      titleColor: '#0f172a',
      fontFamily: '"Source Sans 3", "Segoe UI", sans-serif',
    },
    flowchart: {
      mainBkg: '#dbeafe',
      nodeBorder: '#93c5fd',
      nodeTextColor: '#1e293b',
      clusterBkg: '#f8fafc',
      clusterBorder: '#cbd5e1',
      edgeLabelBackground: '#ffffff',
      defaultLinkColor: '#94a3b8',
    },
    sequence: {
      actorBkg: '#dbeafe',
      actorBorder: '#93c5fd',
      actorTextColor: '#1e293b',
      actorLineColor: '#93c5fd',
      signalColor: '#64748b',
      signalTextColor: '#1e293b',
      labelBoxBkgColor: '#ccfbf1',
      labelBoxBorderColor: '#5eead4',
      labelTextColor: '#1e293b',
      loopTextColor: '#475569',
      activationBkgColor: '#bfdbfe',
      activationBorderColor: '#60a5fa',
      sequenceNumberColor: '#1e293b',
      noteBkgColor: '#fef9c3',
      noteTextColor: '#1e293b',
      noteBorderColor: '#fde047',
    },
    er: {
      attributeBackgroundColorOdd: '#ffffff',
      attributeBackgroundColorEven: '#f0f7ff',
    },
    state: {
      stateBkg: '#dbeafe',
      stateLabelColor: '#1e293b',
      compositeBackground: '#f8fafc',
      compositeTitleBackground: '#e0f2fe',
      compositeBorder: '#93c5fd',
      transitionColor: '#94a3b8',
      transitionLabelColor: '#475569',
      specialStateColor: '#3b82f6',
      errorBkgColor: '#fee2e2',
      errorTextColor: '#991b1b',
    },
    class: {
      classText: '#1e293b',
      fillType0: '#dbeafe',
      fillType1: '#ccfbf1',
      fillType2: '#e0f2fe',
      fillType3: '#bfdbfe',
      fillType4: '#a5f3fc',
      fillType5: '#bae6fd',
      fillType6: '#dbeafe',
      fillType7: '#ccfbf1',
    },
    gantt: {
      sectionBkgColor: '#eff6ff',
      altSectionBkgColor: '#ffffff',
      taskBorderColor: '#93c5fd',
      taskBkgColor: '#dbeafe',
      taskTextColor: '#1e293b',
      taskTextLightColor: '#1e293b',
      taskTextDarkColor: '#1e293b',
      taskTextOutsideColor: '#1e293b',
      activeTaskBorderColor: '#3b82f6',
      activeTaskBkgColor: '#bfdbfe',
      doneTaskBkgColor: '#94a3b8',
      doneTaskBorderColor: '#64748b',
      critBkgColor: '#fee2e2',
      critBorderColor: '#ef4444',
      todayLineColor: '#3b82f6',
    },
    git: {
      git0: '#3b82f6',
      git1: '#0ea5e9',
      git2: '#06b6d4',
      git3: '#6366f1',
      git4: '#8b5cf6',
      git5: '#64748b',
      git6: '#0284c7',
      git7: '#0369a1',
      commitLabelColor: '#1e293b',
      commitLabelBackground: '#f1f5f9',
      gitBranchLabel0: '#000000',
      gitBranchLabel1: '#000000',
      gitBranchLabel2: '#000000',
      gitBranchLabel3: '#1e293b',
      gitBranchLabel4: '#000000',
      gitBranchLabel5: '#1e293b',
      gitBranchLabel6: '#1e293b',
      gitBranchLabel7: '#1e293b',
    },
    pie: {
      pie1: '#3b82f6',
      pie2: '#0ea5e9',
      pie3: '#06b6d4',
      pie4: '#6366f1',
      pie5: '#8b5cf6',
      pie6: '#64748b',
      pie7: '#0284c7',
      pie8: '#0369a1',
      pieTitleTextColor: '#0f172a',
      pieSectionTextColor: '#000000',
      pieStrokeColor: '#ffffff',
    },
    requirement: {
      requirementBackground: '#dbeafe',
      requirementBorderColor: '#93c5fd',
      requirementTextColor: '#1e293b',
      relationColor: '#94a3b8',
      relationLabelBackground: '#ffffff',
      relationLabelColor: '#475569',
    },
    quadrant: {
      quadrant1Fill: '#dbeafe',
      quadrant2Fill: '#e0f2fe',
      quadrant3Fill: '#ccfbf1',
      quadrant4Fill: '#eff6ff',
      quadrant1TextFill: '#1e293b',
      quadrant2TextFill: '#1e293b',
      quadrant3TextFill: '#1e293b',
      quadrant4TextFill: '#1e293b',
      quadrantPointFill: '#3b82f6',
      quadrantPointTextFill: '#000000',
      quadrantXAxisTextFill: '#475569',
      quadrantYAxisTextFill: '#475569',
      quadrantTitleFill: '#0f172a',
    },
    architecture: {
      archEdgeColor: '#94a3b8',
      archEdgeArrowColor: '#94a3b8',
      archGroupBorderColor: '#93c5fd',
    },
    xyChart: {
      plotColorPalette: '#3b82f6,#0ea5e9,#06b6d4,#6366f1,#8b5cf6,#64748b',
    },

    journey: {
      scaleLabelColor: '#1a1a1a',
      cScale0: '#dbeafe', cScaleLabel0: '#1a1a1a',
      cScale1: '#bfdbfe', cScaleLabel1: '#1a1a1a',
      cScale2: '#93c5fd', cScaleLabel2: '#1a1a1a',
      cScale3: '#60a5fa', cScaleLabel3: '#1a1a1a',
      cScale4: '#3b82f6', cScaleLabel4: '#1a1a1a',
      cScale5: '#2563eb', cScaleLabel5: '#ffffff',
      cScale6: '#1d4ed8', cScaleLabel6: '#ffffff',
      cScale7: '#0ea5e9', cScaleLabel7: '#1a1a1a',
      cScale8: '#06b6d4', cScaleLabel8: '#1a1a1a',
      cScale9: '#6366f1', cScaleLabel9: '#ffffff',
      cScale10: '#8b5cf6', cScaleLabel10: '#ffffff',
      cScale11: '#64748b', cScaleLabel11: '#ffffff',
    },
  },
}

export default corporate satisfies ThemePresetDef
