import type { ThemePresetDef } from '../themePresetDefs'

const newsprint: ThemePresetDef = {
  label: 'Newsprint',
  description: 'Editorial serif palette inspired by quality broadsheets',
  configOverrides: {
    look: 'classic' as const,
    fontFamily: '"Lora", "Georgia", serif',
    fontSize: 15,
    flowchart: { curve: 'monotoneX' as const, nodeSpacing: 55, rankSpacing: 58, padding: 18, diagramPadding: 12 },
    sequence: { showSequenceNumbers: false, mirrorActors: false, actorMargin: 55, messageMargin: 36, width: 155 },
    gantt: { barHeight: 22, barGap: 5, topPadding: 50, axisFormat: '%b %d' },
  },
  vars: {
    core: {
      background: '#faf8f4',
      primaryColor: '#f0ece4',
      primaryTextColor: '#1a1a1a',
      primaryBorderColor: '#1a1a1a',
      secondaryColor: '#e8e2d6',
      secondaryTextColor: '#1a1a1a',
      secondaryBorderColor: '#8a8278',
      tertiaryColor: '#f5f1ea',
      tertiaryTextColor: '#333333',
      tertiaryBorderColor: '#b0a898',
      lineColor: '#4a4540',
      titleColor: '#1a1a1a',
      fontFamily: '"Lora", "Georgia", serif',
    },
    flowchart: {
      mainBkg: '#f0ece4',
      nodeBorder: '#1a1a1a',
      nodeTextColor: '#1a1a1a',
      clusterBkg: '#f5f1ea',
      clusterBorder: '#8a8278',
      edgeLabelBackground: '#faf8f4',
      defaultLinkColor: '#4a4540',
    },
    sequence: {
      actorBkg: '#1a1a1a',
      actorBorder: '#1a1a1a',
      actorTextColor: '#faf8f4',
      actorLineColor: '#4a4540',
      signalColor: '#4a4540',
      signalTextColor: '#1a1a1a',
      labelBoxBkgColor: '#f0ece4',
      labelBoxBorderColor: '#8a8278',
      labelTextColor: '#1a1a1a',
      loopTextColor: '#4a4540',
      activationBkgColor: '#e8e2d6',
      activationBorderColor: '#1a1a1a',
      sequenceNumberColor: '#ffffff',
      noteBkgColor: '#f5f1ea',
      noteTextColor: '#1a1a1a',
      noteBorderColor: '#b0a898',
    },
    er: {
      attributeBackgroundColorOdd: '#faf8f4',
      attributeBackgroundColorEven: '#f0ece4',
    },
    state: {
      stateBkg: '#f0ece4',
      stateLabelColor: '#1a1a1a',
      compositeBackground: '#f5f1ea',
      compositeTitleBackground: '#e8e2d6',
      compositeBorder: '#1a1a1a',
      transitionColor: '#4a4540',
      transitionLabelColor: '#1a1a1a',
      specialStateColor: '#4a4540',
      errorBkgColor: '#f5d5d5',
      errorTextColor: '#8b1a1a',
    },
    class: {
      classText: '#1a1a1a',
      fillType0: '#f0ece4',
      fillType1: '#e8e2d6',
      fillType2: '#ddd6c8',
      fillType3: '#d2ccbe',
      fillType4: '#c7c0b2',
      fillType5: '#bcb5a6',
      fillType6: '#b0a898',
      fillType7: '#a49c8c',
    },
    gantt: {
      sectionBkgColor: '#f5f1ea',
      altSectionBkgColor: '#faf8f4',
      taskBorderColor: '#1a1a1a',
      taskBkgColor: '#e8e2d6',
      taskTextColor: '#1a1a1a',
      taskTextLightColor: '#1a1a1a',
      taskTextDarkColor: '#1a1a1a',
      taskTextOutsideColor: '#1a1a1a',
      activeTaskBorderColor: '#c41d1d',
      activeTaskBkgColor: '#f0ece4',
      doneTaskBkgColor: '#b0a898',
      doneTaskBorderColor: '#8a8278',
      critBkgColor: '#f5d5d5',
      critBorderColor: '#c41d1d',
      todayLineColor: '#c41d1d',
    },
    git: {
      git0: '#1a1a1a',
      git1: '#c41d1d',
      git2: '#4a4540',
      git3: '#8a8278',
      git4: '#2e5d4b',
      git5: '#6b3a1a',
      git6: '#6b6b6b',
      git7: '#7a6a52',
      commitLabelColor: '#1a1a1a',
      commitLabelBackground: '#e8e2d6',
      gitBranchLabel0: '#1a1a1a',
      gitBranchLabel1: '#1a1a1a',
      gitBranchLabel2: '#1a1a1a',
      gitBranchLabel3: '#1a1a1a',
      gitBranchLabel4: '#1a1a1a',
      gitBranchLabel5: '#1a1a1a',
      gitBranchLabel6: '#1a1a1a',
      gitBranchLabel7: '#1a1a1a',
    },
    pie: {
      pie1: '#1a1a1a',
      pie2: '#c41d1d',
      pie3: '#6b6b6b',
      pie4: '#7a6a52',
      pie5: '#2e5d4b',
      pie6: '#6b3a1a',
      pie7: '#4a4540',
      pie8: '#8a8278',
      pieTitleTextColor: '#1a1a1a',
      pieSectionTextColor: '#ffffff',
      pieStrokeColor: '#faf8f4',
    },
    requirement: {
      requirementBackground: '#f0ece4',
      requirementBorderColor: '#1a1a1a',
      requirementTextColor: '#1a1a1a',
      relationColor: '#4a4540',
      relationLabelBackground: '#faf8f4',
      relationLabelColor: '#1a1a1a',
    },
    quadrant: {
      quadrant1Fill: '#f0ece4',
      quadrant2Fill: '#e8e2d6',
      quadrant3Fill: '#f5f1ea',
      quadrant4Fill: '#faf8f4',
      quadrant1TextFill: '#1a1a1a',
      quadrant2TextFill: '#1a1a1a',
      quadrant3TextFill: '#1a1a1a',
      quadrant4TextFill: '#1a1a1a',
      quadrantPointFill: '#c41d1d',
      quadrantPointTextFill: '#ffffff',
      quadrantXAxisTextFill: '#4a4540',
      quadrantYAxisTextFill: '#4a4540',
      quadrantTitleFill: '#1a1a1a',
    },
    architecture: {
      archEdgeColor: '#4a4540',
      archEdgeArrowColor: '#4a4540',
      archGroupBorderColor: '#1a1a1a',
    },
    xyChart: {
      plotColorPalette: '#c41d1d,#1a1a1a,#6b6b6b,#7a6a52,#2e5d4b,#6b3a1a',
    },

    journey: {
      scaleLabelColor: '#1a1a1a',
      cScale0: '#f0ece4', cScaleLabel0: '#1a1a1a',
      cScale1: '#e8e2d6', cScaleLabel1: '#1a1a1a',
      cScale2: '#ddd6c8', cScaleLabel2: '#1a1a1a',
      cScale3: '#d2ccbe', cScaleLabel3: '#1a1a1a',
      cScale4: '#c7c0b2', cScaleLabel4: '#1a1a1a',
      cScale5: '#bcb5a6', cScaleLabel5: '#1a1a1a',
      cScale6: '#b0a898', cScaleLabel6: '#1a1a1a',
      cScale7: '#a49c8c', cScaleLabel7: '#1a1a1a',
      cScale8: '#988f80', cScaleLabel8: '#1a1a1a',
      cScale9: '#8a8278', cScaleLabel9: '#1a1a1a',
      cScale10: '#7c756c', cScaleLabel10: '#ffffff',
      cScale11: '#6e6860', cScaleLabel11: '#ffffff',
    },
  },
}

export default newsprint satisfies ThemePresetDef
